INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('566', '0', NULL, '数据列表', NULL, NULL, NULL, NULL, '/system/table/list', '129', '0', NULL, '0', '1', NULL, NULL, '数据管理', 'qx_systemtablelist');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('567', '1', NULL, '字典配置', NULL, NULL, NULL, NULL, '/system/dict/list', '130', '1', NULL, '0', '1', NULL, NULL, '字典管理', 'qx_systemdictlist');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('568', '1', NULL, '字典树', NULL, NULL, NULL, NULL, '/system/dict/treeTable', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdicttreeTable');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('569', '1', NULL, '添加字典', NULL, NULL, NULL, NULL, '/system/dict/addDict', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdictaddDict');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('570', '1', NULL, '选择父级字典', NULL, NULL, NULL, NULL, '/system/dict/choiceParentDict', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdictchoiceParentDict');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('571', '1', NULL, '字典树取值', NULL, NULL, NULL, NULL, '/system/dict/treeData', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdicttreeData');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('572', '1', NULL, '字典查重', NULL, NULL, NULL, NULL, '/system/dict/checkExit', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdictcheckExit');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('573', '1', NULL, '保存字典', NULL, NULL, NULL, NULL, '/system/dict/save', '130', '0', NULL, '0', '1', NULL, NULL, '字典管理', 'qx_systemdictsave');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('574', '1', NULL, '编辑字典', NULL, NULL, NULL, NULL, '/system/dict/editDict', '130', '0', NULL, '0', '0', NULL, NULL, '字典管理', 'qx_systemdicteditDict');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('575', '1', NULL, '修改字典', NULL, NULL, NULL, NULL, '/system/dict/update', '130', '0', NULL, '0', '1', NULL, NULL, '字典管理', 'qx_systemdictupdate');
INSERT INTO `pt_operator` (`id`, `version`, `description`, `names`, `onemany`, `returnparamkeys`, `returnurl`, `rowfilter`, `url`, `moduleids`, `splitpage`, `formtoken`, `ipblack`, `privilege`, `ispv`, `pvtype`, `modulenames`, `formaturl`) VALUES ('576', '0', NULL, '数据表的列管理', NULL, NULL, NULL, NULL, '/system/tablefieid/list', '129', '0', NULL, '0', '1', NULL, NULL, '数据管理', 'qx_systemtablefieidlist');


INSERT INTO `pt_module` (`id`, `version`, `description`, `images`, `isparent`, `names`, `orderids`, `parentmoduleids`, `systemsids`, `numbers`, `iconid`, `url`, `globalization`) VALUES ('128', '0', NULL, NULL, 'true', '参数管理', '123', NULL, '1', 'parameter', '33', NULL, 'parameter');
INSERT INTO `pt_module` (`id`, `version`, `description`, `images`, `isparent`, `names`, `orderids`, `parentmoduleids`, `systemsids`, `numbers`, `iconid`, `url`, `globalization`) VALUES ('129', '0', NULL, NULL, 'false', '数据管理', '124', '128', '1', NULL, NULL, '/system/table/list', 'table Data');
INSERT INTO `pt_module` (`id`, `version`, `description`, `images`, `isparent`, `names`, `orderids`, `parentmoduleids`, `systemsids`, `numbers`, `iconid`, `url`, `globalization`) VALUES ('130', '0', NULL, NULL, 'false', '字典管理', '125', '128', '1', NULL, NULL, '/system/dict/list', 'Dictionaries');
